printing
printError: aResult
	self printException: 'error' result: aResult