printing
printFailure: aResult
	self printException: 'failure' result: aResult